#!/bin/bash

echo "MEV Weather - Scenario Capture Helper"
echo "======================================"
echo ""
echo "Run these commands one at a time:"
echo ""

echo "=== CALM SCENARIOS ==="
echo "1. WBTC-WETH (Blue Chip):"
echo "   Edit capture-live-data.js: targetPair='WBTC-WETH', minTx=30, maxTx=50, duration=15"
echo "   node scripts/capture-live-data.js"
echo ""
echo "2. USDC-WETH (Stablecoin):"
echo "   Edit capture-live-data.js: targetPair='USDC-WETH', minTx=20, maxTx=40, duration=10"
echo "   node scripts/capture-live-data.js"
echo ""
echo "3. LINK-WETH (Quiet Alt):"
echo "   Edit capture-live-data.js: targetPair='LINK-WETH', minTx=25, maxTx=45, duration=15"
echo "   node scripts/capture-live-data.js"
echo ""

echo "=== MODERATE SCENARIOS ==="
echo "4. PEPE-WETH (Active Meme):"
echo "   Edit capture-live-data.js: targetPair='PEPE-WETH', minTx=50, maxTx=80, duration=10"
echo "   node scripts/capture-live-data.js"
echo ""
echo "5. UNI-WETH (DeFi Token):"
echo "   Edit capture-live-data.js: targetPair='UNI-WETH', minTx=40, maxTx=70, duration=12"
echo "   node scripts/capture-live-data.js"
echo ""
echo "6. SHIB-WETH (Trending Alt):"
echo "   Edit capture-live-data.js: targetPair='SHIB-WETH', minTx=50, maxTx=80, duration=10"
echo "   node scripts/capture-live-data.js"
echo ""

echo "=== HIGH/SEVERE SCENARIOS ==="
echo "7. TURBO-WETH (Volatile Meme):"
echo "   Edit capture-live-data.js: targetPair='TURBO-WETH', minTx=60, maxTx=100, duration=8"
echo "   node scripts/capture-live-data.js"
echo ""
echo "8. WOJAK-WETH (High Gas Wars):"
echo "   Edit capture-live-data.js: targetPair='WOJAK-WETH', minTx=60, maxTx=100, duration=8"
echo "   node scripts/capture-live-data.js"
echo ""
echo "9. ALL PAIRS (Mixed Chaos):"
echo "   Edit capture-live-data.js: targetPair=null, minTx=80, maxTx=100, duration=5"
echo "   node scripts/capture-live-data.js"